server:
  port: 8003

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 数据库
spring:
  datasource:
    username: root
    password: 237502
    url: jdbc:mysql://localhost:3306/demo_test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver